### ISSUE TITLE
Why not RxPy?

### ISSUE THREAD

**Issue by frankcarey** [geronimo-iia/async-rx#3]
Hi, came here via looking into your behavior tree implementation and saw this. Just curious if you had seen https://github.com/ReactiveX/RxPY and if so, what your thoughts were.

**Comment by geronimo-iia** [comment]
Hello, 

yes of course I had seen RxPy, and it's for as i can say a very good implementation :)

After taking a try with my behavior tree implementation, I would like to explore the reactive topic with python. And i've seen this RxPy project, and other like https://github.com/dbrattli/aioreactive, etc ...

Before I begin, I would like to say that I have no complains about Rx, and it was my first choice to learn about reactive with python.

In fact, it's just a little details that retain in my mind:

With Rx framework, the implementation did not use async/await functionality, but use scheduler, threading, trampoline by their own. 
The final behavior is more or less the same than async. And it's really good implementation that you could retrieve in other language like node.js for example.

But (always a "but" somewhere) now, we have good async framework like asyncio or https://github.com/dabeaz/curio for example. 
They could replace this hard kernel part. And a project like Rx could focus "only" on reactive specification (and the "only" is an huge amount of "only" in fact ...).
By this way, when you wrote an "rx_publish" you could focus on event/subscribe implementation without too much threading or scheduling details in mind.

So so, so why not using them, and give it a try ?
If you had see my behavior tree implementation, you ever know that "async" sound like chocolat for me... Guilty, I known...

That's why few month ago, I started to wrote this little project.
At first, I had no real specific goal in mind, except than learning and seeing what happens if we use async as core.
Unit test after unit test, in order to correct behaviors, I had something that did not cover all functionality of Rx project but enough (I hope) to share and maybe use it on a real little project that I have in mind (something which deal with events, vision sensors, machine learning in a distributed way, but that's another story!). 
That's why I release it few days ago.

I think the implementation details is one (big) thing. But the most important things, AMHA is how we could play with api and time that we spend to implement our needs. 

Now, project like Rx it's a really huge amount of work, and if you have something to use for production, share with several maintainers, you probably should use RxPy.

By another way, if you're a little bit crazy/adventurous ... give it a try :-)

I hope that's give you an answer, 

And, Thanks to be curious !

Jerome
